# Generated by Django 4.2.2 on 2023-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(help_text='Zadejte typ motoru vozidla - např. spalovací, elektro', max_length=50, verbose_name='Typ motoru')),
                ('etype', models.CharField(blank=True, help_text='Zadejte specifikace motoru vozidla - např. dvouválec, objem', max_length=100, null=True, verbose_name='Bližší specifikace motoru')),
                ('doors', models.FloatField(default=5, help_text='Zadejte číslo odpovídající k počtu dveří vozidla', verbose_name='Počet dveří vozidla')),
            ],
            options={
                'verbose_name': 'Typ',
                'verbose_name_plural': 'Typy',
                'ordering': ['-doors'],
            },
        ),
    ]
