# Generated by Django 4.2.2 on 2023-06-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Zadejte značku auta - např. Škoda, Audi', max_length=60, verbose_name='Značka vozidla')),
                ('y_of_manufacture', models.FloatField(blank=True, help_text='Zadejte rok výroby auta', null=True, verbose_name='Rok výroby')),
                ('mileage', models.FloatField(help_text='Zadejte počet najetých km vozidla', verbose_name='Počet najetých km')),
                ('price', models.FloatField(help_text='Zadejte cenu auta', verbose_name='Cena')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.type', verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auta',
                'ordering': ['-price'],
            },
        ),
    ]
