# Generated by Django 4.2.2 on 2023-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_capacity', models.FloatField(default=10, help_text='Zadejte maximální kapacitu prodejny', verbose_name='Kapacita prodejny')),
                ('city', models.CharField(help_text='Zadejte název obce', max_length=80, verbose_name='Město')),
                ('street', models.CharField(help_text='Zadejte název ulice', max_length=80, verbose_name='Ulice')),
                ('psc', models.FloatField(blank=True, help_text='Zadejte poštvní směrovací číslo', null=True, verbose_name='PSČ')),
            ],
            options={
                'verbose_name': 'Prodejna',
                'verbose_name_plural': 'Prodejny',
                'ordering': ['-cars_capacity'],
            },
        ),
    ]
