# Generated by Django 4.2.2 on 2023-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='psc',
            field=models.FloatField(blank=True, help_text='Zadejte poštovní směrovací číslo', null=True, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.CharField(help_text='Zadejte název ulice + číslo', max_length=80, verbose_name='Ulice'),
        ),
    ]
