# Generated by Django 4.2.2 on 2023-06-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='shop',
        ),
    ]
