# Generated by Django 4.2.2 on 2023-06-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Zadejte roli zákazníka - např. prodávající, nakupující', max_length=80, verbose_name='Role zákazníka')),
                ('note', models.TextField(blank=True, help_text='Zadejte poznámku k zákazníkovi', max_length=100, null=True, verbose_name='Poznámka')),
            ],
            options={
                'verbose_name': 'Zákazník',
                'verbose_name_plural': 'Zákazníci',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.customer', verbose_name='Zákazník'),
        ),
    ]
