# Generated by Django 4.2.2 on 2023-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_customer_car_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cars_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Zadejte maximální kapacitu prodejny', verbose_name='Kapacita prodejny'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='psc',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte poštovní směrovací číslo', null=True, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='type',
            name='doors',
            field=models.PositiveIntegerField(default=5, help_text='Zadejte číslo odpovídající k počtu dveří vozidla', verbose_name='Počet dveří vozidla'),
        ),
    ]
