# Generated by Django 4.2.2 on 2023-06-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_shop_cars_capacity_alter_shop_psc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='customer',
        ),
    ]
