# Generated by Django 4.2.2 on 2023-06-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_car_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(help_text='Zadejte značku auta - např. Škoda Octavia, Audi quattro', max_length=60, verbose_name='Značka vozidla'),
        ),
        migrations.AlterField(
            model_name='car',
            name='y_of_manufacture',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte rok výroby auta', null=True, verbose_name='Rok výroby'),
        ),
    ]
